"""
Django settings for typeidea2 project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# import djcelery
import os
from pathlib import Path


# djcelery.setup_loader()
# CELERY_TIMEZONE = 'Asia/Shanghai'
# BROKER_URL = "redis://127.0.0.1:6379/"
# CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6ymeh4%j6x(%#gusf0xwfssz2t$1=@l#=n+zh*_qh=&xw*_qda'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'ckeditor',
    'ckeditor_uploader',
    'dal',
    'dal_select2',
    'rest_framework',
    # 'django_crontab',

    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',   
    'blog.apps.BlogConfig',
    'blog_param_config.apps.BlogParamConfigConfig',
    'config.apps.ConfigConfig',
    'comment.apps.CommentConfig',
    'typeidea2',  
]

MIDDLEWARE = [
    'blog.middleware.user_id.UserIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'typeidea2.urls'

THEME = 'bootstrap'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'themes', THEME, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'typeidea2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# 解决中文乱码问题
# CRONTAB_COMMAND_PREFIX = 'LANG_ALL=zh_cn.UTF-8'
# 存放log的路径
# CRONJOBS_DIR = "/django_log"
# Log文件名
# CRONJOBS_FILE_NAME = "/CRONJOBS.log"
# 添加定时任务(函数中的输出语句,是输出在.log文件中的)
# CRONJOBS = (
	# 每分钟执行一次TestCrontab App中crontabFun的timedExecution函数，执行后将打印结果存储在log文件中
	#  '2>&1'每项工作执行后要做的事
    # ('*/1 * * * *', 'blog.cron.django_crontab_test'), # 每分钟执行一次
    #('00 11 * * *', 'blog.cron.django_crontab_test',  '>>'+CRONJOBS_DIR+CRONJOBS_FILE_NAME + ' 2>&1'), # 每天11点执行
   # ('0 */1 * * *', 'blog.cron.django_crontab_test',  '>>'+CRONJOBS_DIR+CRONJOBS_FILE_NAME + ' 2>&1'), # 每小时执行一次
    # * * * * *
   	# 分钟(0-59) 小时(0-23) 每个月的哪一天(1-31) 月份(1-12) 周几(0-6)
# )

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = '/tmp/static'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'themes', THEME, "static"),
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 800,
        'tabSpaces': 4,
        'extraPlugins': 'codesnippet',
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
CKEDITOR_UPLOAD_PATH = "article_images"

DEFAULT_FILE_STORAGE = 'typeidea2.storage.WatermarkStorage'
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 2
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# 服务器信息
SIMPLEUI_HOME_INFO = False

# 快速操作
SIMPLEUI_HOME_QUICK = True

# 最近动作
SIMPLEUI_HOME_ACTION = True

# 使用分析
SIMPLEUI_ANALYSIS = True    

# simpleui侧边栏排序
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['博客', '侧边栏', '评论', '管理', '配置表', '认证和授权'],
    'dynamic': True,
}
