# Generated by Django 3.2.14 on 2022-07-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_param_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_config',
            new_name='blog_param_config',
        ),
    ]
